//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenisApp
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Match.
    /// </summary>
    // *** Start programmer edit section *** (Match CustomAttributes)

    // *** End programmer edit section *** (Match CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MatchE", new string[] {
            "Name",
            "StartDate",
            "MaxGameScore",
            "MinGamesForWin",
            "Player1 as \'Игрок 1\' on \'-Игрок1\'",
            "Player1.LastName on \'-Игрок1\'",
            "Player1.FirstName on \'-Игрок1\'",
            "Player1.Rating on \'-Игрок1\'",
            "Player2 as \'Игрок 2\' on \'-Игрок2\'",
            "Player2.LastName on \'-Игрок2\'",
            "Player2.FirstName on \'-Игрок2\'",
            "Player2.Rating on \'-Игрок2\'"}, Hidden=new string[] {
            "Player1.LastName",
            "Player2.LastName"})]
    [AssociatedDetailViewAttribute("MatchE", "Games", "GameE", true, "", "Сыгранные игры", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("MatchE", "Player1", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "LastName")]
    [MasterViewDefineAttribute("MatchE", "Player2", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "LastName")]
    [View("MatchL", new string[] {
            "Name",
            "StartDate",
            "ScoreP1",
            "ScoreP2",
            "Player1.LastName",
            "Player1.FirstName",
            "Player2.LastName",
            "Player2.FirstName"}, Hidden=new string[] {
            "Player1.FirstName",
            "Player2.FirstName"})]
    public class Match : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private System.DateTime fStartDate;
        
        private int fScoreP1;
        
        private int fScoreP2;
        
        private int fMaxGameScore;
        
        private int fMinGamesForWin;
        
        private TenisApp.Player fPlayer1;
        
        private TenisApp.Player fPlayer2;
        
        private TenisApp.DetailArrayOfGame fGames;
        
        // *** Start programmer edit section *** (Match CustomMembers)

        // *** End programmer edit section *** (Match CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Match.Name CustomAttributes)

        // *** End programmer edit section *** (Match.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Match.Name Get start)

                // *** End programmer edit section *** (Match.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Match.Name Get end)

                // *** End programmer edit section *** (Match.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Match.Name Set start)

                // *** End programmer edit section *** (Match.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Match.Name Set end)

                // *** End programmer edit section *** (Match.Name Set end)
            }
        }
        
        /// <summary>
        /// StartDate.
        /// </summary>
        // *** Start programmer edit section *** (Match.StartDate CustomAttributes)

        // *** End programmer edit section *** (Match.StartDate CustomAttributes)
        public virtual System.DateTime StartDate
        {
            get
            {
                // *** Start programmer edit section *** (Match.StartDate Get start)

                // *** End programmer edit section *** (Match.StartDate Get start)
                System.DateTime result = this.fStartDate;
                // *** Start programmer edit section *** (Match.StartDate Get end)

                // *** End programmer edit section *** (Match.StartDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Match.StartDate Set start)

                // *** End programmer edit section *** (Match.StartDate Set start)
                this.fStartDate = value;
                // *** Start programmer edit section *** (Match.StartDate Set end)

                // *** End programmer edit section *** (Match.StartDate Set end)
            }
        }
        
        /// <summary>
        /// ScoreP1.
        /// </summary>
        // *** Start programmer edit section *** (Match.ScoreP1 CustomAttributes)

        // *** End programmer edit section *** (Match.ScoreP1 CustomAttributes)
        public virtual int ScoreP1
        {
            get
            {
                // *** Start programmer edit section *** (Match.ScoreP1 Get start)

                // *** End programmer edit section *** (Match.ScoreP1 Get start)
                int result = this.fScoreP1;
                // *** Start programmer edit section *** (Match.ScoreP1 Get end)

                // *** End programmer edit section *** (Match.ScoreP1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Match.ScoreP1 Set start)

                // *** End programmer edit section *** (Match.ScoreP1 Set start)
                this.fScoreP1 = value;
                // *** Start programmer edit section *** (Match.ScoreP1 Set end)

                // *** End programmer edit section *** (Match.ScoreP1 Set end)
            }
        }
        
        /// <summary>
        /// ScoreP2.
        /// </summary>
        // *** Start programmer edit section *** (Match.ScoreP2 CustomAttributes)

        // *** End programmer edit section *** (Match.ScoreP2 CustomAttributes)
        public virtual int ScoreP2
        {
            get
            {
                // *** Start programmer edit section *** (Match.ScoreP2 Get start)

                // *** End programmer edit section *** (Match.ScoreP2 Get start)
                int result = this.fScoreP2;
                // *** Start programmer edit section *** (Match.ScoreP2 Get end)

                // *** End programmer edit section *** (Match.ScoreP2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Match.ScoreP2 Set start)

                // *** End programmer edit section *** (Match.ScoreP2 Set start)
                this.fScoreP2 = value;
                // *** Start programmer edit section *** (Match.ScoreP2 Set end)

                // *** End programmer edit section *** (Match.ScoreP2 Set end)
            }
        }
        
        /// <summary>
        /// MaxGameScore.
        /// </summary>
        // *** Start programmer edit section *** (Match.MaxGameScore CustomAttributes)

        // *** End programmer edit section *** (Match.MaxGameScore CustomAttributes)
        public virtual int MaxGameScore
        {
            get
            {
                // *** Start programmer edit section *** (Match.MaxGameScore Get start)

                // *** End programmer edit section *** (Match.MaxGameScore Get start)
                int result = this.fMaxGameScore;
                // *** Start programmer edit section *** (Match.MaxGameScore Get end)

                // *** End programmer edit section *** (Match.MaxGameScore Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Match.MaxGameScore Set start)

                // *** End programmer edit section *** (Match.MaxGameScore Set start)
                this.fMaxGameScore = value;
                // *** Start programmer edit section *** (Match.MaxGameScore Set end)

                // *** End programmer edit section *** (Match.MaxGameScore Set end)
            }
        }
        
        /// <summary>
        /// MinGamesForWin.
        /// </summary>
        // *** Start programmer edit section *** (Match.MinGamesForWin CustomAttributes)

        // *** End programmer edit section *** (Match.MinGamesForWin CustomAttributes)
        public virtual int MinGamesForWin
        {
            get
            {
                // *** Start programmer edit section *** (Match.MinGamesForWin Get start)

                // *** End programmer edit section *** (Match.MinGamesForWin Get start)
                int result = this.fMinGamesForWin;
                // *** Start programmer edit section *** (Match.MinGamesForWin Get end)

                // *** End programmer edit section *** (Match.MinGamesForWin Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Match.MinGamesForWin Set start)

                // *** End programmer edit section *** (Match.MinGamesForWin Set start)
                this.fMinGamesForWin = value;
                // *** Start programmer edit section *** (Match.MinGamesForWin Set end)

                // *** End programmer edit section *** (Match.MinGamesForWin Set end)
            }
        }
        
        /// <summary>
        /// Match.
        /// </summary>
        // *** Start programmer edit section *** (Match.Player1 CustomAttributes)

        // *** End programmer edit section *** (Match.Player1 CustomAttributes)
        [PropertyStorage(new string[] {
                "Player1"})]
        [NotNull()]
        public virtual TenisApp.Player Player1
        {
            get
            {
                // *** Start programmer edit section *** (Match.Player1 Get start)

                // *** End programmer edit section *** (Match.Player1 Get start)
                TenisApp.Player result = this.fPlayer1;
                // *** Start programmer edit section *** (Match.Player1 Get end)

                // *** End programmer edit section *** (Match.Player1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Match.Player1 Set start)

                // *** End programmer edit section *** (Match.Player1 Set start)
                this.fPlayer1 = value;
                // *** Start programmer edit section *** (Match.Player1 Set end)

                // *** End programmer edit section *** (Match.Player1 Set end)
            }
        }
        
        /// <summary>
        /// Match.
        /// </summary>
        // *** Start programmer edit section *** (Match.Player2 CustomAttributes)

        // *** End programmer edit section *** (Match.Player2 CustomAttributes)
        [PropertyStorage(new string[] {
                "Player2"})]
        [NotNull()]
        public virtual TenisApp.Player Player2
        {
            get
            {
                // *** Start programmer edit section *** (Match.Player2 Get start)

                // *** End programmer edit section *** (Match.Player2 Get start)
                TenisApp.Player result = this.fPlayer2;
                // *** Start programmer edit section *** (Match.Player2 Get end)

                // *** End programmer edit section *** (Match.Player2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Match.Player2 Set start)

                // *** End programmer edit section *** (Match.Player2 Set start)
                this.fPlayer2 = value;
                // *** Start programmer edit section *** (Match.Player2 Set end)

                // *** End programmer edit section *** (Match.Player2 Set end)
            }
        }
        
        /// <summary>
        /// Match.
        /// </summary>
        // *** Start programmer edit section *** (Match.Games CustomAttributes)

        // *** End programmer edit section *** (Match.Games CustomAttributes)
        public virtual TenisApp.DetailArrayOfGame Games
        {
            get
            {
                // *** Start programmer edit section *** (Match.Games Get start)

                // *** End programmer edit section *** (Match.Games Get start)
                if ((this.fGames == null))
                {
                    this.fGames = new TenisApp.DetailArrayOfGame(this);
                }
                TenisApp.DetailArrayOfGame result = this.fGames;
                // *** Start programmer edit section *** (Match.Games Get end)

                // *** End programmer edit section *** (Match.Games Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Match.Games Set start)

                // *** End programmer edit section *** (Match.Games Set start)
                this.fGames = value;
                // *** Start programmer edit section *** (Match.Games Set end)

                // *** End programmer edit section *** (Match.Games Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MatchE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MatchE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MatchE", typeof(TenisApp.Match));
                }
            }
            
            /// <summary>
            /// "MatchL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MatchL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MatchL", typeof(TenisApp.Match));
                }
            }
        }
    }
}
