//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenisApp
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Player.
    /// </summary>
    // *** Start programmer edit section *** (Player CustomAttributes)

    // *** End programmer edit section *** (Player CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("bpa_PlayerE", new string[] {
            "LastName as \'Last name\'",
            "FirstName as \'First name\'",
            "Rating as \'Rating\'"})]
    [View("bpa_PlayerL", new string[] {
            "LastName as \'Last name\'",
            "FirstName as \'First name\'",
            "Rating as \'Rating\'"})]
    public class Player : ICSSoft.STORMNET.DataObject
    {
        
        private string fLastName;
        
        private string fFirstName;
        
        private int fRating = 1400;
        
        // *** Start programmer edit section *** (Player CustomMembers)

        // *** End programmer edit section *** (Player CustomMembers)

        
        /// <summary>
        /// LastName.
        /// </summary>
        // *** Start programmer edit section *** (Player.LastName CustomAttributes)

        // *** End programmer edit section *** (Player.LastName CustomAttributes)
        [StrLen(255)]
        public virtual string LastName
        {
            get
            {
                // *** Start programmer edit section *** (Player.LastName Get start)

                // *** End programmer edit section *** (Player.LastName Get start)
                string result = this.fLastName;
                // *** Start programmer edit section *** (Player.LastName Get end)

                // *** End programmer edit section *** (Player.LastName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Player.LastName Set start)

                // *** End programmer edit section *** (Player.LastName Set start)
                this.fLastName = value;
                // *** Start programmer edit section *** (Player.LastName Set end)

                // *** End programmer edit section *** (Player.LastName Set end)
            }
        }
        
        /// <summary>
        /// FirstName.
        /// </summary>
        // *** Start programmer edit section *** (Player.FirstName CustomAttributes)

        // *** End programmer edit section *** (Player.FirstName CustomAttributes)
        [StrLen(255)]
        public virtual string FirstName
        {
            get
            {
                // *** Start programmer edit section *** (Player.FirstName Get start)

                // *** End programmer edit section *** (Player.FirstName Get start)
                string result = this.fFirstName;
                // *** Start programmer edit section *** (Player.FirstName Get end)

                // *** End programmer edit section *** (Player.FirstName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Player.FirstName Set start)

                // *** End programmer edit section *** (Player.FirstName Set start)
                this.fFirstName = value;
                // *** Start programmer edit section *** (Player.FirstName Set end)

                // *** End programmer edit section *** (Player.FirstName Set end)
            }
        }
        
        /// <summary>
        /// Rating.
        /// </summary>
        // *** Start programmer edit section *** (Player.Rating CustomAttributes)

        // *** End programmer edit section *** (Player.Rating CustomAttributes)
        public virtual int Rating
        {
            get
            {
                // *** Start programmer edit section *** (Player.Rating Get start)

                // *** End programmer edit section *** (Player.Rating Get start)
                int result = this.fRating;
                // *** Start programmer edit section *** (Player.Rating Get end)

                // *** End programmer edit section *** (Player.Rating Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Player.Rating Set start)

                // *** End programmer edit section *** (Player.Rating Set start)
                this.fRating = value;
                // *** Start programmer edit section *** (Player.Rating Set end)

                // *** End programmer edit section *** (Player.Rating Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "bpa_PlayerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View bpa_PlayerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("bpa_PlayerE", typeof(TenisApp.Player));
                }
            }
            
            /// <summary>
            /// "bpa_PlayerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View bpa_PlayerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("bpa_PlayerL", typeof(TenisApp.Player));
                }
            }
        }
    }
}
